/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f3fcef',
        surface: '#f3fcef',
        'surface-dim': '#d4ddd0',
        'surface-bright': '#f3fcef',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf6ea',
        'surface-container': '#e8f0e4',
        'surface-container-high': '#e2ebde',
        'surface-container-highest': '#dce5d9',
        'surface-variant': '#dce5d9',
        'on-surface': '#161d16',
        'on-surface-variant': '#3d4a3d',
        'on-background': '#161d16',
        outline: '#6d7b6c',
        'outline-variant': '#bccbb9',
        primary: '#006e2f',
        'on-primary': '#ffffff',
        'primary-container': '#22c55e',
        'on-primary-container': '#004b1e',
        'inverse-primary': '#4ae176',
        'surface-tint': '#006e2f',
        secondary: '#006e2d',
        'on-secondary': '#ffffff',
        'secondary-container': '#7cf994',
        'on-secondary-container': '#007230',
        tertiary: '#9e4036',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ff8b7c',
        'on-tertiary-container': '#76231b',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2a322a',
        'inverse-on-surface': '#ebf3e7',
        'primary-fixed': '#6bff8f',
        'primary-fixed-dim': '#4ae176',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005321',
        'secondary-fixed': '#7ffc97',
        'secondary-fixed-dim': '#62df7d',
        'on-secondary-fixed': '#002109',
        'on-secondary-fixed-variant': '#005320',
        'tertiary-fixed': '#ffdad5',
        'tertiary-fixed-dim': '#ffb4a9',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#7f2a21',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        base: '8px',
        'section-padding': '80px',
      },
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Manrope'],
        'headline-lg': ['Manrope'],
        'headline-lg-mobile': ['Manrope'],
        'headline-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'body-md': ['Manrope'],
        'label-md': ['Manrope'],
        'label-sm': ['Manrope'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
