apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: takikb/auth
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: 'nutrition'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth?replicaSet=rs0'
            - name: JWT_KEY 
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_SECURE
              value: "true"
            - name: SMTP_USER
              value: "kebbabtaki@gmail.com"
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASS
---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
