apiVersion : apps/v1
kind : Deployment
metadata :
  name : products-mongo-depl
spec :
  replicas : 1
  selector :
    matchLabels :
      app : products-mongo
  template :
    metadata :
      labels :
        app : products-mongo
    spec :
      containers:
        - name: products-mongo
          image: mongo
          ports :
            - containerPort : 27017

---

apiVersion : v1
kind : Service
metadata :
  name : products-mongo-srv
spec :
  selector :  #find the pod with label app=products-mongo
    app : products-mongo
  ports :
    - name : products-mongo-db
      protocol : TCP
      port : 27017
      targetPort : 27017